In [1]:
import numpy as np
print np.__version__

1.10.4


In [2]:
d = 2
stype = np.dtype([
            ("p1", np.double),
            ("p2", (np.double, (d, d)))
    ])

In [3]:
K = 3
m1 = np.empty((), dtype=stype)
m1['p1'], m1['p2'] = 3., np.arange(d*d).reshape((d,d))
m2 = np.zeros(K, dtype=stype)
m3 = np.zeros(K, dtype=stype)

print m1
for k in range(K):
    print "-" * 5 + str(k) + "-" * 5
    for name in stype.names:
        print "-" * 5 + name + "-" * 5
        print "value", (k+1) * m1[name]
        m2[name][k] = (k+1) * m1[name]
        m3[k][name] = (k+1) * m1[name]
        print "m2 : ", m2[name], m2[name][k]
        print "m3 : ", m3[k], m3[k][name]

(3.0, [[0.0, 1.0], [2.0, 3.0]])
-----0-----
-----p1-----
value 3.0
m2 :  [ 3.  0.  0.] 3.0
m3 :  (3.0, [[0.0, 0.0], [0.0, 0.0]]) 3.0
-----p2-----
value [[ 0.  1.]
 [ 2.  3.]]
m2 :  [[[ 0.  1.]
  [ 2.  3.]]

 [[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]] [[ 0.  1.]
 [ 2.  3.]]
m3 :  (3.0, [[0.0, 1.0], [2.0, 3.0]]) [[ 0.  1.]
 [ 2.  3.]]
-----1-----
-----p1-----
value 6.0
m2 :  [ 3.  6.  0.] 6.0
m3 :  (6.0, [[0.0, 0.0], [0.0, 0.0]]) 6.0
-----p2-----
value [[ 0.  2.]
 [ 4.  6.]]
m2 :  [[[ 0.  1.]
  [ 2.  3.]]

 [[ 0.  2.]
  [ 4.  6.]]

 [[ 0.  0.]
  [ 0.  0.]]] [[ 0.  2.]
 [ 4.  6.]]
m3 :  (6.0, [[0.0, 2.0], [4.0, 6.0]]) [[ 0.  2.]
 [ 4.  6.]]
-----2-----
-----p1-----
value 9.0
m2 :  [ 3.  6.  9.] 9.0
m3 :  (9.0, [[0.0, 0.0], [0.0, 0.0]]) 9.0
-----p2-----
value [[ 0.  3.]
 [ 6.  9.]]
m2 :  [[[ 0.  1.]
  [ 2.  3.]]

 [[ 0.  2.]
  [ 4.  6.]]

 [[ 0.  3.]
  [ 6.  9.]]] [[ 0.  3.]
 [ 6.  9.]]
m3 :  (9.0, [[0.0, 3.0], [6.0, 9.0]]) [[ 0.  3.]
 [ 6.  9.]]
