In [2]:
import numpy as np


In [10]:
x = np.arange(24).reshape(2,3,4)
print(x)
print(x.transpose(1,0,2))
print(x.transpose(1,0,2).reshape(6,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [12 13 14 15]
 [ 4  5  6  7]
 [16 17 18 19]
 [ 8  9 10 11]
 [20 21 22 23]]
